version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jobapp-postgres
    environment:
      POSTGRES_DB: jobapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - jobapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jobapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jobapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - jobapp-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobapp-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - jobapp-network
    restart: unless-stopped

networks:
  jobapp-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: