services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: User_name
      POSTGRES_PASSWORD: Your_Password
      PGDATA: /data/postgres
      #TZ: Asia/Kolkata
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nagamaheshkendole@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-mahesh}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      #TZ: 'Asia/Kolkata'
      #PGADMIN_CONFIG_TZ: 'Asia/Kolkata'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:


